# GTEx model building with CLAMP and PLIER

💡 **Environment:** `clamp-analyses`

This notebook builds latent variable models from GTEx v8 RNA‑seq TPM data using CLAMP and PLIER. It automates downloading and preprocessing the GTEx matrix, creates a Filebacked Big Matrix (FBM), computes an SVD to estimate the model dimension, prepares pathway priors, runs CLAMP (base + full) and PLIER, and saves model outputs (B, Z, summaries) and intermediate files. Configuration and paths are controlled via `config.R`.

# CLAMP

## Load libraries

In [7]:
# Create a timestamp to track the start of the analysis
start_time <- Sys.time()
cat("GTEx CLAMP and PLIER analysis started at:", format(start_time), "\n")

GTEx CLAMP and PLIER analysis started at: 2026-01-24 12:56:15

In [8]:
if (!requireNamespace("PLIER", quietly = TRUE)) {
    devtools::install_github("wgmao/PLIER")
}

library(bigstatsr)
library(data.table)
library(dplyr)
library(rsvd)
library(glmnet)
library(Matrix)
library(knitr)
library(here)
library(PLIER)
library(CLAMP)

source(here("config.R"))

set.seed(config$GTEx$RANDOM_SVD_SEED)

## Output directory

In [9]:
output_data_dir <- config$GTEx$OUTPUT_DIR
dir.create(output_data_dir, showWarnings = FALSE, recursive = TRUE)

output_data_dir

[1] "/home/msubirana/Documents/pivlab/clamp-analyses/output/gtex"

# Settings

In [10]:
block_size <- config$GENERAL$CHUNK_SIZE
N_CORES    <- config$GTEx$N_CORES

## Download GTEx

In [11]:
url <- config$GTEx$URL
dest_dir <-  config$GTEx$DATASET_FOLDER
dest_gz  <- file.path(dest_dir, basename(url))

if (!file.exists(dest_gz)) {
  dir.create(dest_dir, recursive = TRUE, showWarnings = FALSE)
  download.file(url, dest_gz, mode = "wb")
  message("Downloaded to: ", dest_gz)
} else {
  message("File already exists, skipping download.")
}

File already exists, skipping download.

## Preprocess GTEx data

In [12]:
exprs_path  <- file.path(config$GTEx$DATASET_FOLDER, 'GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_tpm.gct.gz')
output_file <- config$GTEx$DATASET_FILE

if (!file.exists(output_file)) {
  dir.create(dirname(output_file), recursive = TRUE, showWarnings = FALSE)
  exprs_data <- read.table(exprs_path, header = TRUE, sep = "\t", skip = 2, check.names = FALSE)
  saveRDS(exprs_data, config$GTEx$DATASET_FILE)
  message("File successfully written to: ", config$GTEx$DATASET_FILE)
} else {
  message("Output file already exists. Skipping.")
}

# Aggregate in-place by 'description'
gtex <- readRDS(here(config$GTEx$DATASET_FILE))
gtex <- as.data.table(gtex)
aggregated_gtex <- gtex[, lapply(.SD, sum), by = Description, .SDcols = is.numeric]

genes <- aggregated_gtex$Description
samples <- colnames(aggregated_gtex[, -1])
data_mat <- as.matrix(aggregated_gtex[, -1])

Output file already exists. Skipping.

In [13]:
fbm_files <- c(
  file.path(output_data_dir, "FBMgtex.bk"),
  file.path(output_data_dir, "FBMgtex_preproc.bk"),
  file.path(output_data_dir, "FBMgtex_preproc_filtered.bk"),
  file.path(output_data_dir, "FBMgtex_preproc_filtered.rds")
)

for (f in fbm_files) {
  if (file.exists(f)) {
    res <- unlink(f)
    if (identical(res, 0L)) {
      message("✅ Removed existing FBM file: ", f)
    } else {
      warning("⚠️ Failed to remove: ", f)
    }
  } else {
    message("ℹ️ Not found, skipping: ", f)
  }
}

✅ Removed existing FBM file: /home/msubirana/Documents/pivlab/clamp-analyses/output/gtex/FBMgtex.bk

ℹ️ Not found, skipping: /home/msubirana/Documents/pivlab/clamp-analyses/output/gtex/FBMgtex_preproc.bk

ℹ️ Not found, skipping: /home/msubirana/Documents/pivlab/clamp-analyses/output/gtex/FBMgtex_preproc_filtered.bk

ℹ️ Not found, skipping: /home/msubirana/Documents/pivlab/clamp-analyses/output/gtex/FBMgtex_preproc_filtered.rds

In [14]:
# Create the FBM
fbm_file <- file.path(output_data_dir, "FBMgtex")
gtexFBM <- FBM(nrow = nrow(data_mat), ncol = ncol(data_mat), backingfile = fbm_file, create_bk = T)

# Populate it with data
n_blocks <- ceiling(nrow(aggregated_gtex) / block_size)

for (i in 1:n_blocks) {
  start_row <- (i-1) * block_size + 1
  end_row <- min(i * block_size, nrow(data_mat))
  
  gtexFBM[start_row:end_row, ] <- as.matrix(data_mat[start_row:end_row, ])
}

# Preprocess and z‑score FBM

prep_gtex <- preprocessCLAMPFBM(
  fbm        = gtexFBM,
  mean_cutoff= config$GTEx$GENES_MEAN_CUTOFF,
  var_cutoff = config$GTEx$GENES_VAR_CUTOFF,
  ncores=N_CORES
)

gtex_fbm_filt <- prep_gtex$fbm_filtered
gtex_rowStats <- prep_gtex$rowStats

Applying log2 transformation

No NA values found

Check overlap genes with GTEx v8 RNA-seq data and TWAS gene list

In [15]:
twas_genes <- read.csv(here('output/creating_twas_gwas_list/gene_list_union_mashr_and_elastic_net_with_phi.csv'))
head(twas_genes)

  Ensembl_ID      Gene_Symbol   Ensembl_ID_w_version en_Adipose_Subcutaneous
1 ENSG00000238009 RP11-34P13.7  ENSG00000238009.6    0
2 ENSG00000228463 AP006222.2    ENSG00000228463.9    0
3 ENSG00000237094 RP4-669L17.10 ENSG00000237094.11   0
4 ENSG00000230021 RP5-857K21.4  ENSG00000230021.8    0
5 ENSG00000237491 RP11-206L10.9 ENSG00000237491.8    1
6 ENSG00000177757 FAM87B        ENSG00000177757.2    1
  en_Adipose_Visceral_Omentum en_Adrenal_Gland en_Artery_Aorta
1 0                           0                0
2 1                           1                0
3 0                           0                0
4 0                           0                0
5 1                           1                1
6 1                           1                1
  en_Artery_Coronary en_Artery_Tibial en_Brain_Amygdala ⋯
1 0                  0                0                 ⋯
2 0                  0                0                 ⋯
3 0                  0                0                 ⋯
4 0                  0                0                 ⋯
5 1                  1                1                 ⋯
6 1                  1                0                 ⋯
  mashr_Skin_Not_Sun_Exposed_Suprapubic mashr_Skin_Sun_Exposed_Lower_leg
1 0                                     0
2 1                                     1
3 1                                     0
4 0                                     0
5 1                                     1
6 1                                     1
  mashr_Small_Intestine_Terminal_Ileum mashr_Spleen mashr_Stomach mashr_Testis
1 0                                    1            0             1
2 0                                    0            1             1
3 0                                    0            0             0
4 0                                    0            0             1
5 1                                    1            1             1
6 1                                    1            1             1
  mashr_Thyroid mashr_Uterus mashr_Vagina mashr_Whole_Blood
1 0             0            0            1
2 1             1            1            0
3 1             0            0            0
4 1             0            0            0
5 1             1            1            1
6 1             1            1            1

In [16]:
overlap_genes <- intersect(genes[prep_gtex$kept_rows], twas_genes$Gene_Symbol)

percent_overlap <- (length(overlap_genes) / length(twas_genes$Gene_Symbol)) * 100

cat("Number of overlapping genes:", length(overlap_genes), "\n")
cat("Percentage overlap (relative to TWAS genes):", round(percent_overlap, 2), "%\n")

Number of overlapping genes: 16488
Percentage overlap (relative to TWAS genes): 72.24 %

In [17]:
zscoreCLAMPFBM(gtex_fbm_filt, gtex_rowStats, ncores=N_CORES)
gtex_genes <- genes[prep_gtex$kept_rows]

Applying Z-score transformation

In [18]:
saveRDS(samples, file = file.path(output_data_dir, "gtex_samples.rds"))

In [19]:
saveRDS(gtex_genes, file = file.path(output_data_dir, "gtex_genes.rds"))

In [20]:
saveRDS(gtex_fbm_filt, file = file.path(output_data_dir, "gtex_fbm_filt.rds"))

In [21]:
df_gtex_fbm_filt <- as.data.frame(as.matrix(gtex_fbm_filt[]))

In [22]:
colnames(df_gtex_fbm_filt) <- samples

In [23]:
rownames(df_gtex_fbm_filt) <- gtex_genes

In [24]:
head(df_gtex_fbm_filt)

              GTEX-1117F-0226-SM-5GZZ7 GTEX-1117F-0426-SM-5EGHI
WASH7P         1.44614308               0.1466590
RP11-34P13.15 -0.21703290              -1.2491072
RP11-34P13.16  0.05000362              -1.2529810
RP11-34P13.18  0.80964288              -0.4648762
AP006222.2     0.60340589              -0.6590192
MTND1P23      -0.28701222               0.4584699
              GTEX-1117F-0526-SM-5EGHJ GTEX-1117F-0626-SM-5N9CS
WASH7P         1.15444418               1.8411744
RP11-34P13.15 -0.71067536              -0.5458638
RP11-34P13.16 -1.26148519              -0.7514709
RP11-34P13.18  0.60984294               0.6852051
AP006222.2    -0.22788724              -0.3186479
MTND1P23      -0.04655404              -0.6834497
              GTEX-1117F-0726-SM-5GIEN GTEX-1117F-1326-SM-5EGHH
WASH7P        -0.07922225               0.6559264
RP11-34P13.15 -0.88156172              -0.4026354
RP11-34P13.16 -0.77242737              -0.3766090
RP11-34P13.18 -1.14329360              -0.5356296
AP006222.2    -0.75919490              -0.8022825
MTND1P23      -0.28493094               0.5112355
              GTEX-1117F-2426-SM-5EGGH GTEX-1117F-2526-SM-5GZY6
WASH7P         1.9780371                2.5806060
RP11-34P13.15 -0.5965898                0.2922380
RP11-34P13.16 -0.9801061                0.4096420
RP11-34P13.18  1.4716736                1.0668942
AP006222.2    -0.8073561               -0.9128508
MTND1P23      -0.4015529               -0.5931863
              GTEX-1117F-2826-SM-5GZXL GTEX-1117F-2926-SM-5GZYI ⋯
WASH7P         1.6749832                2.04978755              ⋯
RP11-34P13.15 -0.4949213                0.05590706              ⋯
RP11-34P13.16 -0.3255995               -0.06358077              ⋯
RP11-34P13.18  0.1565502                0.90028575              ⋯
AP006222.2    -0.3943123               -0.90819239              ⋯
MTND1P23       0.1299671               -0.25562386              ⋯
              GTEX-ZZPU-1126-SM-5N9CW GTEX-ZZPU-1226-SM-5N9CK
WASH7P        -1.0148940              -0.59314323
RP11-34P13.15 -0.1934056               0.33783682
RP11-34P13.16  0.1692925               0.70250273
RP11-34P13.18 -1.3100707              -0.67305864
AP006222.2     0.1568485               1.49184552
MTND1P23       1.0400459              -0.03813723
              GTEX-ZZPU-1326-SM-5GZWS GTEX-ZZPU-1426-SM-5GZZ6
WASH7P         0.65505136             -0.5693505
RP11-34P13.15  1.59084836              0.4045636
RP11-34P13.16  1.43810645              0.6769784
RP11-34P13.18 -0.05994370             -1.0821739
AP006222.2     1.31865074             -0.1807585
MTND1P23      -0.04317319             -0.1047992
              GTEX-ZZPU-1826-SM-5E43L GTEX-ZZPU-2126-SM-5EGIU
WASH7P        -0.48892918             0.2077396965
RP11-34P13.15  0.05473854             1.0872298726
RP11-34P13.16  0.17310765             1.2674193527
RP11-34P13.18 -0.70715756             0.0894613755
AP006222.2     0.13219755             2.1816052692
MTND1P23       0.06352471             0.0003105984
              GTEX-ZZPU-2226-SM-5EGIV GTEX-ZZPU-2426-SM-5E44I
WASH7P        -0.8016505              -0.28439422
RP11-34P13.15  0.5077824              -0.19027836
RP11-34P13.16  0.8571877              -0.10447332
RP11-34P13.18 -1.3990557              -0.65677160
AP006222.2    -0.3754781              -0.03196266
MTND1P23      -0.2519768              -0.01557983
              GTEX-ZZPU-2626-SM-5E45Y GTEX-ZZPU-2726-SM-5NQ8O
WASH7P        -1.6336384              -0.65163455
RP11-34P13.15 -0.9777920               0.24859783
RP11-34P13.16 -1.0448862               0.46041845
RP11-34P13.18 -1.7141016              -0.37942569
AP006222.2    -0.2097524               3.06398139
MTND1P23       0.3048702              -0.02531932

In [25]:
saveRDS(df_gtex_fbm_filt, file = file.path(output_data_dir, "df_gtex_fbm_filt.rds"))
write.csv(df_gtex_fbm_filt, file = file.path(output_data_dir, "df_gtex_fbm_filt.csv"))

## SVD computation

In [26]:
if (!file.exists(file.path(output_data_dir, "gtex_svdRes.rds"))) {

  g_fb <- nrow(gtex_fbm_filt)
  samples_fb <- ncol(gtex_fbm_filt)
  SVD_K_gtex <- min(g_fb, samples_fb) - 1

  message("Using SVD K = ", SVD_K_gtex)

  if (N_CORES > 1) {
    # disable BLAS parallelization when parallelizing
    options(bigstatsr.check.parallel.blas = FALSE)
    blas_nproc <- getOption("default.nproc.blas")
    options(default.nproc.blas = NULL)
  }

  gtex_svdRes <- big_randomSVD(
    gtex_fbm_filt,
    k = SVD_K_gtex,
    ncores = N_CORES
  )

  saveRDS(gtex_svdRes, file = file.path(output_data_dir, "gtex_svdRes.rds"))

  if (N_CORES > 1) {
    # restore previous state
    options(bigstatsr.check.parallel.blas = TRUE)
    options(default.nproc.blas = blas_nproc)
  }

} else {
  message("gtex_svdRes already exists, skipping SVD computation.")
}

gtex_svdRes already exists, skipping SVD computation.

## Estimate K for CLAMP

In [27]:
gtex_fbm_filt <- readRDS(file.path(output_data_dir, "gtex_fbm_filt.rds"))
gtex_svdRes <- readRDS(file.path(output_data_dir, "gtex_svdRes.rds"))

In [28]:
CLAMP_K_gtex <- num.pc(list(d = gtex_svdRes$d)) * 2
message("Inferred CLAMP K = ", CLAMP_K_gtex)

Inferred CLAMP K = 412

In [29]:
saveRDS(CLAMP_K_gtex, file = file.path(output_data_dir, "CLAMP_K_gtex.rds"))

write.csv(
  as.data.frame(CLAMP_K_gtex),
  file = file.path(output_data_dir, "CLAMP_K_gtex.csv"),
  row.names = TRUE
)

## CLAMPbase

In [ ]:
gtex_baseRes <- CLAMPbase(
  Y      = gtex_fbm_filt,
  svdres = gtex_svdRes,
  trace  = TRUE,
  clamp_k = CLAMP_K_gtex
)

In [ ]:
gtex_baseRes$Z <- data.frame(gtex_baseRes$Z)
rownames(gtex_baseRes$Z) <- gtex_genes
head(gtex_baseRes$Z)

gtex_baseRes$B <- data.frame(gtex_baseRes$B)
colnames(gtex_baseRes$B) <- samples
head(gtex_baseRes$B)

In [ ]:
saveRDS(gtex_baseRes, file = file.path(output_data_dir, "CLAMPbase.rds"))

In [ ]:
model_dir <- file.path(output_data_dir, "CLAMPbase")
dir.create(model_dir, showWarnings = FALSE, recursive = TRUE)

B <- gtex_baseRes$B
write.csv(B, file.path(model_dir, "B.csv"))

Z <- gtex_baseRes$Z
write.csv(Z, file.path(model_dir, "Z.csv"))

## Prepare pathway priors

In [ ]:
gtex_gmtList <- list(
  KEGG = getGMT("https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=KEGG_2021_Human"),
  BP = getGMT("https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=GO_Biological_Process_2025"),
  GTEx_Tissues = getGMT("https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=GTEx_Tissues_V8_2023")
)

# prefix each gene‐set name with its library to guarantee uniqueness
for(lib in names(gtex_gmtList)) {
  names(gtex_gmtList[[lib]]) <- paste0(lib, "_", names(gtex_gmtList[[lib]]))
}

gtex_pathMat <- gmtListToSparseMat(gtex_gmtList)
gtex_matched <- getMatchedPathwayMat(gtex_pathMat, gtex_genes)
gtex_chatObj <- getChat(gtex_matched)

## CLAMPfull

In [ ]:
gtex_fullRes <- CLAMPfull(
    Y = gtex_fbm_filt,
    svdres = gtex_svdRes,
    priorMat = gtex_matched,
    clamp.base.result = gtex_baseRes,
    use_cpp = TRUE,
    trace = TRUE,
    clamp_k = CLAMP_K_gtex
  )

In [ ]:
gtex_baseRes$Z <- data.frame(gtex_baseRes$Z)
rownames(gtex_baseRes$Z) <- gtex_genes
head(gtex_baseRes$Z)

gtex_baseRes$B <- data.frame(gtex_baseRes$B)
colnames(gtex_baseRes$B) <- samples
head(gtex_baseRes$B)

gtex_fullRes$summary <- gtex_fullRes$summary %>%
    dplyr::rename(LV = LV_index)  %>% 
    dplyr::mutate(LV = paste0('LV', LV))

In [ ]:
saveRDS(gtex_fullRes, file = file.path(output_data_dir, "CLAMPfull.rds"))

In [ ]:
gtex_fullRes = readRDS(here('output/gtex/CLAMPfull.rds'))

In [ ]:
samples = readRDS(file.path(here('output/gtex/gtex_samples.rds')))
colnames(gtex_fullRes$B) = samples
head(gtex_fullRes$B)

In [ ]:
model_dir <- file.path(output_data_dir, "CLAMPfull")
dir.create(model_dir, showWarnings = FALSE, recursive = TRUE)

B <- gtex_fullRes$B
write.csv(B, file.path(model_dir, "B.csv"))

Z <- gtex_fullRes$Z
write.csv(Z, file.path(model_dir, "Z.csv"))

summary <- gtex_fullRes$summary
write.csv(summary, file.path(model_dir, "summary.csv"))

In [ ]:
# Create a timestamp to track the end of the analysis
end_time <- Sys.time()
elapsed_time <- end_time - start_time
cat("GTEx CLAMP analysis completed at:", format(end_time), "\n")
cat("Total elapsed time:", format(elapsed_time), "\n")

# PLIER

Run PLIER with the same inputs

In [ ]:
gtex_plier = PLIER::PLIER(
    gtex_fbm_filt[], 
    as.matrix(gtex_matched), 
    svdres = gtex_svdRes, 
    Chat = as.matrix(gtex_chatObj), 
    doCrossval = TRUE, 
    k = CLAMP_K_gtex
  )

In [ ]:
colnames(gtex_plier$Z) <- paste0('LV', seq_len(ncol(gtex_plier$Z)))

In [ ]:
head(gtex_plier$Z)
dim(gtex_plier$Z)

In [ ]:
gtex_plier$summary <- gtex_plier$summary %>%
    dplyr::rename(LV = `LV index`)  %>% 
    dplyr::mutate(LV = paste0('LV', LV))

In [ ]:
head(gtex_plier$summary)

In [ ]:
head(gtex_plier$B)
dim(gtex_plier$B)

In [ ]:
colnames(gtex_plier$B) <- samples

In [ ]:
saveRDS(gtex_plier, file = file.path(output_data_dir, "PLIER.rds"))

In [ ]:
model_dir <- file.path(output_data_dir, "PLIER")
dir.create(model_dir, showWarnings = FALSE, recursive = TRUE)

B <- gtex_plier$B
write.csv(B, file.path(model_dir, "B.csv"))

Z <- gtex_plier$Z
write.csv(Z, file.path(model_dir, "Z.csv"))

summary <- gtex_plier$summary
write.csv(summary, file.path(model_dir, "summary.csv"))